name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cpputest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        cd high_level_code/test
        make
